### ISSUE TITLE
真机ios下代码高亮显示异常（字号变大）

### ISSUE THREAD

**Issue by okaychen** [Lemonreds/hexo-theme-nayo#59]
Pc Android都正常，ios真机下代码高亮字号变大：

建议加下面代码：
```css
html{
    -webkit-text-size-adjust: none;
}

```
可以参考：https://bugs.webkit.org/show_bug.cgi?id=56543
